# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectCard', '0002_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('stack', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=50)),
            ],
        ),
    ]
