# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectCard', '0005_auto_20170401_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='stack',
            new_name='code',
        ),
    ]
