# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectCard', '0007_auto_20170401_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_choices',
            field=models.CharField(choices=[('Software', 'Software'), ('Stack', 'Stack'), ('Language', 'Language')], default='Software', max_length=10),
        ),
    ]
