# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectCard', '0008_card_card_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_choices',
            new_name='card_choice',
        ),
    ]
