# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectCard', '0009_auto_20170401_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='group',
            field=models.IntegerField(default=1),
        ),
    ]
